export const GET_CURRENCY_EXCHANGE_RATES = 'GET_CURRENCY_EXCHANGE_RATES';
export const SET_CURRENCY_EXCHANGE_RATES = 'SET_CURRENCY_EXCHANGE_RATES';
export const ADD_CURRENCY = 'ADD_CURRENCY';
export const SET_BASE_CURRENCY = 'SET_BASE_CURRENCY';
export const REMOVE_CURRENCY = 'REMOVE_CURRENCY';
export const ADD_CURRENCY_AMOUNT = 'ADD_CURRENCY_AMOUNT';